//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Omicron.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_Omicron.Views.Shared.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new student.
        /// </summary>
        public static string Addnewstudent {
            get {
                return ResourceManager.GetString("Addnewstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new student.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Registered Course.
        /// </summary>
        public static string EditRegisteredCourse {
            get {
                return ResourceManager.GetString("EditRegisteredCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Student Information.
        /// </summary>
        public static string EditStudentInformation {
            get {
                return ResourceManager.GetString("EditStudentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already register in this course *.
        /// </summary>
        public static string ExistsRegistered {
            get {
                return ResourceManager.GetString("ExistsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already exist *.
        /// </summary>
        public static string ExistsStudent {
            get {
                return ResourceManager.GetString("ExistsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new student.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration System.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Student.
        /// </summary>
        public static string RegisternewStudent {
            get {
                return ResourceManager.GetString("RegisternewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday date is required *.
        /// </summary>
        public static string RequiredBirthday {
            get {
                return ResourceManager.GetString("RequiredBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is required *.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required *.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required *.
        /// </summary>
        public static string RequiredPhone {
            get {
                return ResourceManager.GetString("RequiredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name:.
        /// </summary>
        public static string searchBy {
            get {
                return ResourceManager.GetString("searchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select course.
        /// </summary>
        public static string Selectcourse {
            get {
                return ResourceManager.GetString("Selectcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string StudentAddress {
            get {
                return ResourceManager.GetString("StudentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student email.
        /// </summary>
        public static string StudentEmail {
            get {
                return ResourceManager.GetString("StudentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Dees.
        /// </summary>
        public static string StudentFees {
            get {
                return ResourceManager.GetString("StudentFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student List.
        /// </summary>
        public static string StudentLink {
            get {
                return ResourceManager.GetString("StudentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string StudentMobile {
            get {
                return ResourceManager.GetString("StudentMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students list.
        /// </summary>
        public static string title1 {
            get {
                return ResourceManager.GetString("title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered students.
        /// </summary>
        public static string title2 {
            get {
                return ResourceManager.GetString("title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Email address..
        /// </summary>
        public static string validationEmail {
            get {
                return ResourceManager.GetString("validationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Phone number..
        /// </summary>
        public static string validationNumber {
            get {
                return ResourceManager.GetString("validationNumber", resourceCulture);
            }
        }
    }
}
